#!/bin/bash

find . -name "*.zip" | while read filename; do
	unzip -o -d "`dirname "$filename"`" "$filename";
done

find . -name "*.rar" | while read filename; do
	unar -o "`dirname "$filename"`" "$filename";
done

find . -name "*.7z" | while read filename;
	7z e -o{"`dirname "$filename"`"} "$filename";
done	
