#!/bin/bash

find . -name "*.zip" | while read filename; do
	unzip -d "`dirname "$filename"`" "$filename";
done

find . -name "*.rar" | while read filename; do
	unar -o "`dirname "$filename"`" "$filename";
done

find . -name "*.7z" | while read filename; do
	7z e -o"`dirname "$filename"`" "$filename";
done

