#!/usr/bin/env bash

# script to manage wildfly servers

# variables
COMMAND=""
SERVER_NAME=""
SERVER_TYPE="wildfly"
SERVER_DIR="/home/plechowicz/Development/jbosses/"
SERVER_PATH=""

# shows usage
function show_help {
cat << EOF
usage: $0 server_name {start|stop|log|restart|help} [ server_type [ server_dir ]]
EOF
}

# read variables from input arguments
function read_variables {
    if [ -z "$1" ]; then
	    echo -e "\nerror: name of server must be provided\n"
	    show_help
	    exit 1
    fi
    SERVER_NAME="$1"

    [[ ! -z "$2" ]] && COMMAND="$2";
    [[ ! -z "$3" ]] && SERVER_TYPE="$3";
    [[ ! -z "$4" ]] && SERVER_DIR="$4";

    SERVER_PATH="${SERVER_DIR}${SERVER_NAME}/${SERVER_TYPE}/"
}

# for debug purposes
function print_variables {
    echo $1 $2 $3 $4
}

function start {
    ${SERVER_PATH}bin/standalone.sh $5
}

function stop {
    ${SERVER_PATH}bin/jboss-cli.sh --connect shutdown
}

function restart {
    stop
    start
}

function log {
    colortail -f -n 50 "${SERVER_PATH}standalone/log/server.log"
}

read_variables $@

#Main flow of the program
case "$2" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    log)
        log
        ;;
    restart)
        restart
        ;;
    help | h)
        show_help
        exit
        ;;
    *)
        echo "Unrecognized command"
        show_help
        exit 1
esac